//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foursnac.wsSonicBliss {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sonicbliss.com.br", ConfigurationName="wsSonicBliss.wsSBSoap")]
    public interface wsSBSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/getPedidos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foursnac.wsSonicBliss.Pedidos[] getPedidos(string ID_ESTABELECIMENTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/getPedidos", ReplyAction="*")]
        System.Threading.Tasks.Task<Foursnac.wsSonicBliss.Pedidos[]> getPedidosAsync(string ID_ESTABELECIMENTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/getPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foursnac.wsSonicBliss.Pedidos getPedido(string ID_ESTABELECIMENTO, string ID_PEDIDO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/getPedido", ReplyAction="*")]
        System.Threading.Tasks.Task<Foursnac.wsSonicBliss.Pedidos> getPedidoAsync(string ID_ESTABELECIMENTO, string ID_PEDIDO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/SomethingTodo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foursnac.wsSonicBliss.HasSomethingToDo[] SomethingTodo(string ID_ESTABELECIMENTO, string ID_MAQUINA, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/SomethingTodo", ReplyAction="*")]
        System.Threading.Tasks.Task<Foursnac.wsSonicBliss.HasSomethingToDo[]> SomethingTodoAsync(string ID_ESTABELECIMENTO, string ID_MAQUINA, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/getDadosEstabelecimento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foursnac.wsSonicBliss.Estabelecimento getDadosEstabelecimento(string ID_ESTABELECIMENTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/getDadosEstabelecimento", ReplyAction="*")]
        System.Threading.Tasks.Task<Foursnac.wsSonicBliss.Estabelecimento> getDadosEstabelecimentoAsync(string ID_ESTABELECIMENTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/getDadosEstabelecimentoByCNPJ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foursnac.wsSonicBliss.Estabelecimento getDadosEstabelecimentoByCNPJ(string CNPJ, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/getDadosEstabelecimentoByCNPJ", ReplyAction="*")]
        System.Threading.Tasks.Task<Foursnac.wsSonicBliss.Estabelecimento> getDadosEstabelecimentoByCNPJAsync(string CNPJ, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/getInfos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foursnac.wsSonicBliss.Informacao getInfos(string ID_ESTABLECIMENTO, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/getInfos", ReplyAction="*")]
        System.Threading.Tasks.Task<Foursnac.wsSonicBliss.Informacao> getInfosAsync(string ID_ESTABLECIMENTO, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/getItensPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foursnac.wsSonicBliss.Itens[] getItensPedido(string ID_ESTABELECIMENTO, string ID_PEDIDO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/getItensPedido", ReplyAction="*")]
        System.Threading.Tasks.Task<Foursnac.wsSonicBliss.Itens[]> getItensPedidoAsync(string ID_ESTABELECIMENTO, string ID_PEDIDO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/getItensAdicioanis", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foursnac.wsSonicBliss.ITENS_ADICIONAIS[] getItensAdicioanis(string ID_PEDIDO_ITEM, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/getItensAdicioanis", ReplyAction="*")]
        System.Threading.Tasks.Task<Foursnac.wsSonicBliss.ITENS_ADICIONAIS[]> getItensAdicioanisAsync(string ID_PEDIDO_ITEM, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/DadosCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foursnac.wsSonicBliss.Cliente DadosCliente(string ID_CLIENTE, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/DadosCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Foursnac.wsSonicBliss.Cliente> DadosClienteAsync(string ID_CLIENTE, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/LoadParameter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoadParameter(string P_NOME, string P_TIPO, string ID_ESTABELECIMENTO, string K_FOURSNAC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/LoadParameter", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LoadParameterAsync(string P_NOME, string P_TIPO, string ID_ESTABELECIMENTO, string K_FOURSNAC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/SetMaquinaImpressao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SetMaquinaImpressao(string ID_ESTABELECIMENTO, string MAQUINA, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/SetMaquinaImpressao", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SetMaquinaImpressaoAsync(string ID_ESTABELECIMENTO, string MAQUINA, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/TimeClear", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool TimeClear(string ID_SB, string ID_ESTABELECIMENTO, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/TimeClear", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> TimeClearAsync(string ID_SB, string ID_ESTABELECIMENTO, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/SalvarParametro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SalvarParametro(string P_NOME, string P_VALOR, string P_TIPO, string ID_ESTABELECIMENTO, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/SalvarParametro", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SalvarParametroAsync(string P_NOME, string P_VALOR, string P_TIPO, string ID_ESTABELECIMENTO, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/getEnderecoUsuarioweb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foursnac.wsSonicBliss.EnderecoWeb getEnderecoUsuarioweb(string ID_CLIENTE, string ID_ENDERECO_WEB, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/getEnderecoUsuarioweb", ReplyAction="*")]
        System.Threading.Tasks.Task<Foursnac.wsSonicBliss.EnderecoWeb> getEnderecoUsuariowebAsync(string ID_CLIENTE, string ID_ENDERECO_WEB, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/listarFaturamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foursnac.wsSonicBliss.FATURAMENTO[] listarFaturamento(string ID_ESTABELECIMENTO, string DATA_INICIO, string DATA_FINAL, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/listarFaturamento", ReplyAction="*")]
        System.Threading.Tasks.Task<Foursnac.wsSonicBliss.FATURAMENTO[]> listarFaturamentoAsync(string ID_ESTABELECIMENTO, string DATA_INICIO, string DATA_FINAL, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/ListarEstabelecimentos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foursnac.wsSonicBliss.Estabelecimento[] ListarEstabelecimentos(string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/ListarEstabelecimentos", ReplyAction="*")]
        System.Threading.Tasks.Task<Foursnac.wsSonicBliss.Estabelecimento[]> ListarEstabelecimentosAsync(string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/ConsultarCep", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ConsultarCep(string WEB_KEY, string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/ConsultarCep", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ConsultarCepAsync(string WEB_KEY, string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/ConfirmaUrlEstabelecimento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ConfirmaUrlEstabelecimento(string WEB_KEY, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/ConfirmaUrlEstabelecimento", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ConfirmaUrlEstabelecimentoAsync(string WEB_KEY, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/EnviarEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool EnviarEmail(string ID_PEDIDO, string ID_ESTABELECIMENTO, string ASSUNTO, string BODY_NAME, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/EnviarEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EnviarEmailAsync(string ID_PEDIDO, string ID_ESTABELECIMENTO, string ASSUNTO, string BODY_NAME, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/EnviarEmailPadrao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool EnviarEmailPadrao(string[] CAMPOS, string CORPO, string BODY_NAME, string STR_TO, string STR_NOME, string ASSUNTO, string STR_FROM, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/EnviarEmailPadrao", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EnviarEmailPadraoAsync(string[] CAMPOS, string CORPO, string BODY_NAME, string STR_TO, string STR_NOME, string ASSUNTO, string STR_FROM, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/FinalizaToDo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool FinalizaToDo(string ID_TODO, string ID_ESTABELECIMENTO, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/FinalizaToDo", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> FinalizaToDoAsync(string ID_TODO, string ID_ESTABELECIMENTO, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/CreateUsuarioWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void CreateUsuarioWeb(string JsonUsuarioWeb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/CreateUsuarioWeb", ReplyAction="*")]
        System.Threading.Tasks.Task CreateUsuarioWebAsync(string JsonUsuarioWeb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/JSONStringify", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void JSONStringify(object VALOR, string WEB_KEY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sonicbliss.com.br/JSONStringify", ReplyAction="*")]
        System.Threading.Tasks.Task JSONStringifyAsync(object VALOR, string WEB_KEY);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sonicbliss.com.br")]
    public partial class Pedidos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string idEstabelecimentoField;
        
        private string bandeiraField;
        
        private string dataField;
        
        private string enderecoField;
        
        private string formaPgtoField;
        
        private string idUsuariowebField;
        
        private string motivoField;
        
        private string numeroPedidoField;
        
        private string obsField;
        
        private string statusField;
        
        private string tipoField;
        
        private string tipoCartaoField;
        
        private string totalItensField;
        
        private string totalPedidoField;
        
        private string trocoParaField;
        
        private string freteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdEstabelecimento {
            get {
                return this.idEstabelecimentoField;
            }
            set {
                this.idEstabelecimentoField = value;
                this.RaisePropertyChanged("IdEstabelecimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Bandeira {
            get {
                return this.bandeiraField;
            }
            set {
                this.bandeiraField = value;
                this.RaisePropertyChanged("Bandeira");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
                this.RaisePropertyChanged("Endereco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FormaPgto {
            get {
                return this.formaPgtoField;
            }
            set {
                this.formaPgtoField = value;
                this.RaisePropertyChanged("FormaPgto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IdUsuarioweb {
            get {
                return this.idUsuariowebField;
            }
            set {
                this.idUsuariowebField = value;
                this.RaisePropertyChanged("IdUsuarioweb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
                this.RaisePropertyChanged("Motivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string NumeroPedido {
            get {
                return this.numeroPedidoField;
            }
            set {
                this.numeroPedidoField = value;
                this.RaisePropertyChanged("NumeroPedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Obs {
            get {
                return this.obsField;
            }
            set {
                this.obsField = value;
                this.RaisePropertyChanged("Obs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string TipoCartao {
            get {
                return this.tipoCartaoField;
            }
            set {
                this.tipoCartaoField = value;
                this.RaisePropertyChanged("TipoCartao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TotalItens {
            get {
                return this.totalItensField;
            }
            set {
                this.totalItensField = value;
                this.RaisePropertyChanged("TotalItens");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string TotalPedido {
            get {
                return this.totalPedidoField;
            }
            set {
                this.totalPedidoField = value;
                this.RaisePropertyChanged("TotalPedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string TrocoPara {
            get {
                return this.trocoParaField;
            }
            set {
                this.trocoParaField = value;
                this.RaisePropertyChanged("TrocoPara");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Frete {
            get {
                return this.freteField;
            }
            set {
                this.freteField = value;
                this.RaisePropertyChanged("Frete");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sonicbliss.com.br")]
    public partial class FATURAMENTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idEstabelecimentoField;
        
        private string estabelecimentoField;
        
        private string totalPedidosField;
        
        private string totalValorField;
        
        private string qtdeDeliveryField;
        
        private string qtdePickupField;
        
        private string totalDeliveryField;
        
        private string totalPickupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdEstabelecimento {
            get {
                return this.idEstabelecimentoField;
            }
            set {
                this.idEstabelecimentoField = value;
                this.RaisePropertyChanged("IdEstabelecimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Estabelecimento {
            get {
                return this.estabelecimentoField;
            }
            set {
                this.estabelecimentoField = value;
                this.RaisePropertyChanged("Estabelecimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TotalPedidos {
            get {
                return this.totalPedidosField;
            }
            set {
                this.totalPedidosField = value;
                this.RaisePropertyChanged("TotalPedidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TotalValor {
            get {
                return this.totalValorField;
            }
            set {
                this.totalValorField = value;
                this.RaisePropertyChanged("TotalValor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string QtdeDelivery {
            get {
                return this.qtdeDeliveryField;
            }
            set {
                this.qtdeDeliveryField = value;
                this.RaisePropertyChanged("QtdeDelivery");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string QtdePickup {
            get {
                return this.qtdePickupField;
            }
            set {
                this.qtdePickupField = value;
                this.RaisePropertyChanged("QtdePickup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TotalDelivery {
            get {
                return this.totalDeliveryField;
            }
            set {
                this.totalDeliveryField = value;
                this.RaisePropertyChanged("TotalDelivery");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TotalPickup {
            get {
                return this.totalPickupField;
            }
            set {
                this.totalPickupField = value;
                this.RaisePropertyChanged("TotalPickup");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sonicbliss.com.br")]
    public partial class EnderecoWeb : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string cepField;
        
        private string estadoField;
        
        private string cidadeField;
        
        private string bairroField;
        
        private string logradouroField;
        
        private string numeroField;
        
        private string complementoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
                this.RaisePropertyChanged("Cep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
                this.RaisePropertyChanged("Cidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
                this.RaisePropertyChanged("Bairro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
                this.RaisePropertyChanged("Logradouro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("Numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
                this.RaisePropertyChanged("Complemento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sonicbliss.com.br")]
    public partial class Cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nomeField;
        
        private string sexoField;
        
        private string celularField;
        
        private string emailField;
        
        private string nascimentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("Sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
                this.RaisePropertyChanged("Celular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Nascimento {
            get {
                return this.nascimentoField;
            }
            set {
                this.nascimentoField = value;
                this.RaisePropertyChanged("Nascimento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sonicbliss.com.br")]
    public partial class ITENS_ADICIONAIS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string idPedidoItemField;
        
        private string idAdicionalField;
        
        private string nomeField;
        
        private string valorField;
        
        private string totalField;
        
        private string qtdeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdPedidoItem {
            get {
                return this.idPedidoItemField;
            }
            set {
                this.idPedidoItemField = value;
                this.RaisePropertyChanged("IdPedidoItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdAdicional {
            get {
                return this.idAdicionalField;
            }
            set {
                this.idAdicionalField = value;
                this.RaisePropertyChanged("IdAdicional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("Valor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Qtde {
            get {
                return this.qtdeField;
            }
            set {
                this.qtdeField = value;
                this.RaisePropertyChanged("Qtde");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sonicbliss.com.br")]
    public partial class Itens : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nomeField;
        
        private string idPedidoField;
        
        private string idItemField;
        
        private string qtdeField;
        
        private string valorField;
        
        private string totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdPedido {
            get {
                return this.idPedidoField;
            }
            set {
                this.idPedidoField = value;
                this.RaisePropertyChanged("IdPedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IdItem {
            get {
                return this.idItemField;
            }
            set {
                this.idItemField = value;
                this.RaisePropertyChanged("IdItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Qtde {
            get {
                return this.qtdeField;
            }
            set {
                this.qtdeField = value;
                this.RaisePropertyChanged("Qtde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("Valor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sonicbliss.com.br")]
    public partial class Informacao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string cnpjField;
        
        private string emailField;
        
        private string siteField;
        
        private string sobreField;
        
        private string telefoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
                this.RaisePropertyChanged("Cnpj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
                this.RaisePropertyChanged("Site");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Sobre {
            get {
                return this.sobreField;
            }
            set {
                this.sobreField = value;
                this.RaisePropertyChanged("Sobre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
                this.RaisePropertyChanged("Telefone");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sonicbliss.com.br")]
    public partial class Estabelecimento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string faturamentoField;
        
        private string nomeField;
        
        private string qtdVendasField;
        
        private string celularField;
        
        private string idModalidadeField;
        
        private string idPlanoField;
        
        private string idTipoField;
        
        private string idUsuarioField;
        
        private string sloganField;
        
        private string statusField;
        
        private string viewsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Faturamento {
            get {
                return this.faturamentoField;
            }
            set {
                this.faturamentoField = value;
                this.RaisePropertyChanged("Faturamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string QtdVendas {
            get {
                return this.qtdVendasField;
            }
            set {
                this.qtdVendasField = value;
                this.RaisePropertyChanged("QtdVendas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
                this.RaisePropertyChanged("Celular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string IdModalidade {
            get {
                return this.idModalidadeField;
            }
            set {
                this.idModalidadeField = value;
                this.RaisePropertyChanged("IdModalidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IdPlano {
            get {
                return this.idPlanoField;
            }
            set {
                this.idPlanoField = value;
                this.RaisePropertyChanged("IdPlano");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string IdTipo {
            get {
                return this.idTipoField;
            }
            set {
                this.idTipoField = value;
                this.RaisePropertyChanged("IdTipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("IdUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Slogan {
            get {
                return this.sloganField;
            }
            set {
                this.sloganField = value;
                this.RaisePropertyChanged("Slogan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Views {
            get {
                return this.viewsField;
            }
            set {
                this.viewsField = value;
                this.RaisePropertyChanged("Views");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sonicbliss.com.br")]
    public partial class HasSomethingToDo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string idEstabelecimentoField;
        
        private string dataField;
        
        private string whatField;
        
        private string whoField;
        
        private string inProgressField;
        
        private string isDoneField;
        
        private string chaveField;
        
        private string origemField;
        
        private string idSBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdEstabelecimento {
            get {
                return this.idEstabelecimentoField;
            }
            set {
                this.idEstabelecimentoField = value;
                this.RaisePropertyChanged("IdEstabelecimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string What {
            get {
                return this.whatField;
            }
            set {
                this.whatField = value;
                this.RaisePropertyChanged("What");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Who {
            get {
                return this.whoField;
            }
            set {
                this.whoField = value;
                this.RaisePropertyChanged("Who");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string InProgress {
            get {
                return this.inProgressField;
            }
            set {
                this.inProgressField = value;
                this.RaisePropertyChanged("InProgress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IsDone {
            get {
                return this.isDoneField;
            }
            set {
                this.isDoneField = value;
                this.RaisePropertyChanged("IsDone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Chave {
            get {
                return this.chaveField;
            }
            set {
                this.chaveField = value;
                this.RaisePropertyChanged("Chave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Origem {
            get {
                return this.origemField;
            }
            set {
                this.origemField = value;
                this.RaisePropertyChanged("Origem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string IdSB {
            get {
                return this.idSBField;
            }
            set {
                this.idSBField = value;
                this.RaisePropertyChanged("IdSB");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsSBSoapChannel : Foursnac.wsSonicBliss.wsSBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsSBSoapClient : System.ServiceModel.ClientBase<Foursnac.wsSonicBliss.wsSBSoap>, Foursnac.wsSonicBliss.wsSBSoap {
        
        public wsSBSoapClient() {
        }
        
        public wsSBSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsSBSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSBSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Foursnac.wsSonicBliss.Pedidos[] getPedidos(string ID_ESTABELECIMENTO) {
            return base.Channel.getPedidos(ID_ESTABELECIMENTO);
        }
        
        public System.Threading.Tasks.Task<Foursnac.wsSonicBliss.Pedidos[]> getPedidosAsync(string ID_ESTABELECIMENTO) {
            return base.Channel.getPedidosAsync(ID_ESTABELECIMENTO);
        }
        
        public Foursnac.wsSonicBliss.Pedidos getPedido(string ID_ESTABELECIMENTO, string ID_PEDIDO) {
            return base.Channel.getPedido(ID_ESTABELECIMENTO, ID_PEDIDO);
        }
        
        public System.Threading.Tasks.Task<Foursnac.wsSonicBliss.Pedidos> getPedidoAsync(string ID_ESTABELECIMENTO, string ID_PEDIDO) {
            return base.Channel.getPedidoAsync(ID_ESTABELECIMENTO, ID_PEDIDO);
        }
        
        public Foursnac.wsSonicBliss.HasSomethingToDo[] SomethingTodo(string ID_ESTABELECIMENTO, string ID_MAQUINA, string WEB_KEY) {
            return base.Channel.SomethingTodo(ID_ESTABELECIMENTO, ID_MAQUINA, WEB_KEY);
        }
        
        public System.Threading.Tasks.Task<Foursnac.wsSonicBliss.HasSomethingToDo[]> SomethingTodoAsync(string ID_ESTABELECIMENTO, string ID_MAQUINA, string WEB_KEY) {
            return base.Channel.SomethingTodoAsync(ID_ESTABELECIMENTO, ID_MAQUINA, WEB_KEY);
        }
        
        public Foursnac.wsSonicBliss.Estabelecimento getDadosEstabelecimento(string ID_ESTABELECIMENTO) {
            return base.Channel.getDadosEstabelecimento(ID_ESTABELECIMENTO);
        }
        
        public System.Threading.Tasks.Task<Foursnac.wsSonicBliss.Estabelecimento> getDadosEstabelecimentoAsync(string ID_ESTABELECIMENTO) {
            return base.Channel.getDadosEstabelecimentoAsync(ID_ESTABELECIMENTO);
        }
        
        public Foursnac.wsSonicBliss.Estabelecimento getDadosEstabelecimentoByCNPJ(string CNPJ, string WEB_KEY) {
            return base.Channel.getDadosEstabelecimentoByCNPJ(CNPJ, WEB_KEY);
        }
        
        public System.Threading.Tasks.Task<Foursnac.wsSonicBliss.Estabelecimento> getDadosEstabelecimentoByCNPJAsync(string CNPJ, string WEB_KEY) {
            return base.Channel.getDadosEstabelecimentoByCNPJAsync(CNPJ, WEB_KEY);
        }
        
        public Foursnac.wsSonicBliss.Informacao getInfos(string ID_ESTABLECIMENTO, string WEB_KEY) {
            return base.Channel.getInfos(ID_ESTABLECIMENTO, WEB_KEY);
        }
        
        public System.Threading.Tasks.Task<Foursnac.wsSonicBliss.Informacao> getInfosAsync(string ID_ESTABLECIMENTO, string WEB_KEY) {
            return base.Channel.getInfosAsync(ID_ESTABLECIMENTO, WEB_KEY);
        }
        
        public Foursnac.wsSonicBliss.Itens[] getItensPedido(string ID_ESTABELECIMENTO, string ID_PEDIDO) {
            return base.Channel.getItensPedido(ID_ESTABELECIMENTO, ID_PEDIDO);
        }
        
        public System.Threading.Tasks.Task<Foursnac.wsSonicBliss.Itens[]> getItensPedidoAsync(string ID_ESTABELECIMENTO, string ID_PEDIDO) {
            return base.Channel.getItensPedidoAsync(ID_ESTABELECIMENTO, ID_PEDIDO);
        }
        
        public Foursnac.wsSonicBliss.ITENS_ADICIONAIS[] getItensAdicioanis(string ID_PEDIDO_ITEM, string WEB_KEY) {
            return base.Channel.getItensAdicioanis(ID_PEDIDO_ITEM, WEB_KEY);
        }
        
        public System.Threading.Tasks.Task<Foursnac.wsSonicBliss.ITENS_ADICIONAIS[]> getItensAdicioanisAsync(string ID_PEDIDO_ITEM, string WEB_KEY) {
            return base.Channel.getItensAdicioanisAsync(ID_PEDIDO_ITEM, WEB_KEY);
        }
        
        public Foursnac.wsSonicBliss.Cliente DadosCliente(string ID_CLIENTE, string WEB_KEY) {
            return base.Channel.DadosCliente(ID_CLIENTE, WEB_KEY);
        }
        
        public System.Threading.Tasks.Task<Foursnac.wsSonicBliss.Cliente> DadosClienteAsync(string ID_CLIENTE, string WEB_KEY) {
            return base.Channel.DadosClienteAsync(ID_CLIENTE, WEB_KEY);
        }
        
        public string LoadParameter(string P_NOME, string P_TIPO, string ID_ESTABELECIMENTO, string K_FOURSNAC) {
            return base.Channel.LoadParameter(P_NOME, P_TIPO, ID_ESTABELECIMENTO, K_FOURSNAC);
        }
        
        public System.Threading.Tasks.Task<string> LoadParameterAsync(string P_NOME, string P_TIPO, string ID_ESTABELECIMENTO, string K_FOURSNAC) {
            return base.Channel.LoadParameterAsync(P_NOME, P_TIPO, ID_ESTABELECIMENTO, K_FOURSNAC);
        }
        
        public string SetMaquinaImpressao(string ID_ESTABELECIMENTO, string MAQUINA, string WEB_KEY) {
            return base.Channel.SetMaquinaImpressao(ID_ESTABELECIMENTO, MAQUINA, WEB_KEY);
        }
        
        public System.Threading.Tasks.Task<string> SetMaquinaImpressaoAsync(string ID_ESTABELECIMENTO, string MAQUINA, string WEB_KEY) {
            return base.Channel.SetMaquinaImpressaoAsync(ID_ESTABELECIMENTO, MAQUINA, WEB_KEY);
        }
        
        public bool TimeClear(string ID_SB, string ID_ESTABELECIMENTO, string WEB_KEY) {
            return base.Channel.TimeClear(ID_SB, ID_ESTABELECIMENTO, WEB_KEY);
        }
        
        public System.Threading.Tasks.Task<bool> TimeClearAsync(string ID_SB, string ID_ESTABELECIMENTO, string WEB_KEY) {
            return base.Channel.TimeClearAsync(ID_SB, ID_ESTABELECIMENTO, WEB_KEY);
        }
        
        public bool SalvarParametro(string P_NOME, string P_VALOR, string P_TIPO, string ID_ESTABELECIMENTO, string WEB_KEY) {
            return base.Channel.SalvarParametro(P_NOME, P_VALOR, P_TIPO, ID_ESTABELECIMENTO, WEB_KEY);
        }
        
        public System.Threading.Tasks.Task<bool> SalvarParametroAsync(string P_NOME, string P_VALOR, string P_TIPO, string ID_ESTABELECIMENTO, string WEB_KEY) {
            return base.Channel.SalvarParametroAsync(P_NOME, P_VALOR, P_TIPO, ID_ESTABELECIMENTO, WEB_KEY);
        }
        
        public Foursnac.wsSonicBliss.EnderecoWeb getEnderecoUsuarioweb(string ID_CLIENTE, string ID_ENDERECO_WEB, string WEB_KEY) {
            return base.Channel.getEnderecoUsuarioweb(ID_CLIENTE, ID_ENDERECO_WEB, WEB_KEY);
        }
        
        public System.Threading.Tasks.Task<Foursnac.wsSonicBliss.EnderecoWeb> getEnderecoUsuariowebAsync(string ID_CLIENTE, string ID_ENDERECO_WEB, string WEB_KEY) {
            return base.Channel.getEnderecoUsuariowebAsync(ID_CLIENTE, ID_ENDERECO_WEB, WEB_KEY);
        }
        
        public Foursnac.wsSonicBliss.FATURAMENTO[] listarFaturamento(string ID_ESTABELECIMENTO, string DATA_INICIO, string DATA_FINAL, string WEB_KEY) {
            return base.Channel.listarFaturamento(ID_ESTABELECIMENTO, DATA_INICIO, DATA_FINAL, WEB_KEY);
        }
        
        public System.Threading.Tasks.Task<Foursnac.wsSonicBliss.FATURAMENTO[]> listarFaturamentoAsync(string ID_ESTABELECIMENTO, string DATA_INICIO, string DATA_FINAL, string WEB_KEY) {
            return base.Channel.listarFaturamentoAsync(ID_ESTABELECIMENTO, DATA_INICIO, DATA_FINAL, WEB_KEY);
        }
        
        public Foursnac.wsSonicBliss.Estabelecimento[] ListarEstabelecimentos(string WEB_KEY) {
            return base.Channel.ListarEstabelecimentos(WEB_KEY);
        }
        
        public System.Threading.Tasks.Task<Foursnac.wsSonicBliss.Estabelecimento[]> ListarEstabelecimentosAsync(string WEB_KEY) {
            return base.Channel.ListarEstabelecimentosAsync(WEB_KEY);
        }
        
        public string ConsultarCep(string WEB_KEY, string cep) {
            return base.Channel.ConsultarCep(WEB_KEY, cep);
        }
        
        public System.Threading.Tasks.Task<string> ConsultarCepAsync(string WEB_KEY, string cep) {
            return base.Channel.ConsultarCepAsync(WEB_KEY, cep);
        }
        
        public bool ConfirmaUrlEstabelecimento(string WEB_KEY, string url) {
            return base.Channel.ConfirmaUrlEstabelecimento(WEB_KEY, url);
        }
        
        public System.Threading.Tasks.Task<bool> ConfirmaUrlEstabelecimentoAsync(string WEB_KEY, string url) {
            return base.Channel.ConfirmaUrlEstabelecimentoAsync(WEB_KEY, url);
        }
        
        public bool EnviarEmail(string ID_PEDIDO, string ID_ESTABELECIMENTO, string ASSUNTO, string BODY_NAME, string WEB_KEY) {
            return base.Channel.EnviarEmail(ID_PEDIDO, ID_ESTABELECIMENTO, ASSUNTO, BODY_NAME, WEB_KEY);
        }
        
        public System.Threading.Tasks.Task<bool> EnviarEmailAsync(string ID_PEDIDO, string ID_ESTABELECIMENTO, string ASSUNTO, string BODY_NAME, string WEB_KEY) {
            return base.Channel.EnviarEmailAsync(ID_PEDIDO, ID_ESTABELECIMENTO, ASSUNTO, BODY_NAME, WEB_KEY);
        }
        
        public bool EnviarEmailPadrao(string[] CAMPOS, string CORPO, string BODY_NAME, string STR_TO, string STR_NOME, string ASSUNTO, string STR_FROM, string WEB_KEY) {
            return base.Channel.EnviarEmailPadrao(CAMPOS, CORPO, BODY_NAME, STR_TO, STR_NOME, ASSUNTO, STR_FROM, WEB_KEY);
        }
        
        public System.Threading.Tasks.Task<bool> EnviarEmailPadraoAsync(string[] CAMPOS, string CORPO, string BODY_NAME, string STR_TO, string STR_NOME, string ASSUNTO, string STR_FROM, string WEB_KEY) {
            return base.Channel.EnviarEmailPadraoAsync(CAMPOS, CORPO, BODY_NAME, STR_TO, STR_NOME, ASSUNTO, STR_FROM, WEB_KEY);
        }
        
        public bool FinalizaToDo(string ID_TODO, string ID_ESTABELECIMENTO, string WEB_KEY) {
            return base.Channel.FinalizaToDo(ID_TODO, ID_ESTABELECIMENTO, WEB_KEY);
        }
        
        public System.Threading.Tasks.Task<bool> FinalizaToDoAsync(string ID_TODO, string ID_ESTABELECIMENTO, string WEB_KEY) {
            return base.Channel.FinalizaToDoAsync(ID_TODO, ID_ESTABELECIMENTO, WEB_KEY);
        }
        
        public void CreateUsuarioWeb(string JsonUsuarioWeb) {
            base.Channel.CreateUsuarioWeb(JsonUsuarioWeb);
        }
        
        public System.Threading.Tasks.Task CreateUsuarioWebAsync(string JsonUsuarioWeb) {
            return base.Channel.CreateUsuarioWebAsync(JsonUsuarioWeb);
        }
        
        public void JSONStringify(object VALOR, string WEB_KEY) {
            base.Channel.JSONStringify(VALOR, WEB_KEY);
        }
        
        public System.Threading.Tasks.Task JSONStringifyAsync(object VALOR, string WEB_KEY) {
            return base.Channel.JSONStringifyAsync(VALOR, WEB_KEY);
        }
    }
}
